---
title: "Atelier 4"
author: "Isaure Garrigue"
date: "04/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
nutriage <- read.csv("~/Desktop/Biostatisique/nutriage.csv")
names(nutriage)
```

$X  \equiv$ taille cm $N( \mu, \sigma)$

```{r}
mu<-mean(nutriage$taille)
sigma<-sd(nutriage$taille)
mu
sigma
proba_negative<-pnorm(0,mu,sigma)
proba_negative
```
$X = e^y$ avec $y \sim N(\mu,\sigma)$ alors $y = \ln(X) $ 

```{r}
y <- log(nutriage$taille)
hist(y)
mu_y <- mean(y)
sigma_y <- sd(y)
mu_y
sigma_y
```

Est-ce que $y$ est une distribution normale ?

```{r}
z <- (y-mu_y)/sigma_y
mean(z)
sd(z)
n <- length(z)
N <- rnorm(n)
qqplot(z,N,xlim=c(-3,3),ylim=c(-3,3))
par (new=T)
plot(z,z,type="l",col="red",xlim=c(-3,3),ylim=c(-3,3))
```
Simulations

```{r}
n <- 1000
simulation <- rnorm(n,mu_y,sigma_y)
taille_simulation <- exp(simulation)
hist(taille_simulation)
```

$X  \equiv$ poids cm $N( \mu, \sigma)$

```{r}
mu<-mean(nutriage$poids)
sigma<-sd(nutriage$poids)
mu
sigma
proba_negative<-pnorm(0,mu,sigma)
proba_negative
```

$X = e^y$ avec $y \sim N(\mu,\sigma)$ alors $y = \ln(X) $ 

```{r}
y <- log(nutriage$poids)
hist(y)
mu_y <- mean(y)
sigma_y <- sd(y)
mu_y
sigma_y
```
Est-ce que $y$ est une distribution normale ?

```{r}
z <- (y-mu_y)/sigma_y
mean(z)
sd(z)
n <- length(z)
N <- rnorm(n)
qqplot(z,N,xlim=c(-3,3),ylim=c(-3,3))
par (new=T)
plot(z,z,type="l",col="red",xlim=c(-3,3),ylim=c(-3,3))
```

```{r}
taille_h <- nutriage$taille[nutriage$sexe==1]
taille_f <- nutriage$taille[nutriage$sexe==2]
mean(taille_h)
sd(taille_h)
mean(taille_f)
sd(taille_f)
length(taille_h)
length(taille_f)
```
Normal chez les hommes 

```{r}
log_taille_h <- log(taille_h)
mu_logh <- mean(log_taille_h )
sigma_logh <- sd(log_taille_h )
z_h <- (log_taille_h-mu_logh)/sigma_logh
N <- rnorm(length(taille_h))
qqplot(z_h,N,xlim=c(-3,3),ylim=c(-3,3))
par (new=T)
plot(z_h,z_h,type="l",col="red",xlim=c(-3,3),ylim=c(-3,3))
```

```{r}
log_taille_f <- log(taille_f)
mu_logh <- mean(log_taille_f )
sigma_logh <- sd(log_taille_f )
z_f <- (log_taille_f-mu_logh)/sigma_logh
N <- rnorm(length(taille_f))
qqplot(z_f,N,xlim=c(-3,3),ylim=c(-3,3))
par (new=T)
plot(z_f,z_f,type="l",col="red",xlim=c(-3,3),ylim=c(-3,3))
````

```{r}
mean(nutriage$cafe)
var(nutriage$cafe)
lambda <- (mean(nutriage$cafe)+var(nutriage$cafe))/2
lambda
simulation_p <- rpois(1000,lambda)
boxplot(simulation_p)
```



```{r}
mean(nutriage$the)
var(nutriage$the)
lambda <- (mean(nutriage$the)+var(nutriage$the))/2
lambda
simulation_p <- rpois(1000,lambda)
boxplot(simulation_p)
```
